// AUTH TYPES
export const CHECK_AUTH = 'CHECK_AUTH'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// USER TYPES
export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAIL = 'CURRENT_USER_FAIL'

// Tweet TYPES
export const COMPOSE_TWEET = 'COMPOSE_TWEET'
export const TWEETS_REQUEST = 'TWEETS_REQUEST'
export const HOME_TWEETS_SUCCESS = 'HOME_TWEETS_SUCCESS'
export const EXPLORE_TWEETS_SUCCESS = 'EXPLORE_TWEETS_SUCCESS'
export const USER_TWEETS_SUCCESS = 'USER_TWEETS_SUCCESS'
export const TWEETS_ERROR = 'TWEETS_ERROR'
export const CURRENT_TWEET_REQUEST = 'CURRENT_TWEET_REQUEST'
export const CURRENT_TWEET_SUCCESS = 'CURRENT_TWEET_SUCCESS'
export const CURRENT_TWEET_ERROR = 'CURRENT_TWEET_ERROR'
export const REPLIES_SUCCESS = 'REPLIES_SUCCESS'
export const REPLIES_ERROR = 'REPLIES_ERROR'
